name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: pip install mypy types-requests



      # Lint & format (fail if issues)
      - run: ruff check .
      - run: black --check .

      # # Type check
      # - run: mypy src

      # Tests + coverage
      - run: pytest -q --cov=src --cov-report=xml --cov-report=term

      # Upload coverage to Codecov (no token needed for public repos)
      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
